name: deepTools bamPEFragmentSize
url: https://deeptools.readthedocs.io/en/latest/content/tools/bamPEFragmentSize.html
description: >
  For usage information about ``deepTools bamPEFragmentSize``, please see the [documentation](https://deeptools.readthedocs.io/en/latest/content/tools/bamPEFragmentSize.html).
  For more information about ``deepTools``, also see the [source code](https://github.com/deeptools/deepTools).

options:
  histogram:
    flags: ["--histogram", "-hist", "-o"]
    format: "gzipped matrix file"
    variable: "hist"
    extension: ".png"
    required: true
  raw_lengths:
    flag: "--outRawFragmentLengths"
    format: "tab-separated table of fragment lengths and occurrences"
    variable: "raw"
    extension: ".tab"
    required: false

authors:
  - Niek Wit
input:
  - bams: List of BAM files (.bam)
  - blacklist: Optional BED file with regions to skip (.bed)
output:
  - hist: Fragment size histogram (.png)
  - raw: Raw fragment lengths (.tab) (optional)
params:
  - title: Title of the plot
  - extra: Optional parameters given to bamPEFragmentSize
